services:
  - type: web
    name: frogpaper-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 900
    envVars:
      - key: PORT
        value: 5000
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: HUGGINGFACE_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    disk:
      name: data
      mountPath: /app/static/images
      sizeGB: 1